# Generated by Django 4.1.1 on 2022-09-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("techblog_app", "0003_alter_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
    ]
