# Generated by Django 4.1.1 on 2022-09-11 22:43

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("techblog_app", "0004_remove_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
