# Generated by Django 4.1.1 on 2022-09-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techblog_app", "0005_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
