# Generated by Django 4.1.1 on 2022-09-12 00:55

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("techblog_app", "0006_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
