# Generated by Django 4.1.1 on 2022-09-13 08:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("techblog_app", "0008_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
