# Generated by Django 4.1.1 on 2022-09-13 09:31

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("techblog_app", "0009_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
