# Generated by Django 4.1.1 on 2022-09-13 15:21

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("techblog_app", "0010_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
